# task
data_dir: ''
work_dir: '' # experiment directory.
infer: False # infer
seed: 1234
debug: False
resume_from_checkpoint: ''

#############
# dataset
#############
test_num: 100
indexed_ds: True
endless_ds: False
sort_by_len: True

#########
# train and eval
#########
save_ckpt: True
clip_grad_norm: 0
accumulate_grad_batches: 1
log_interval: 100
num_sanity_val_steps: 5  # steps of validation at the beginning
check_val_every_n_epoch: 10
val_check_interval: 2000
max_epochs: 1000
max_updates: 160000
max_tokens: 31250
max_sentences: -1
max_eval_tokens: -1
max_eval_sentences: -1
use_training: False
use_amp: False

########
# other setting
########
show_progress_bar: True
